# arguments for dataset
  dataset: ijmond
  data_root: /content/drive/MyDrive/devlab/ijmond-unimatch-v2/bbox_learn/dataset
  nclass: 2
  crop_size: 518

# arguments for training
  epochs: 60
  batch_size: 32 # per GPU x 1 GPU
  lr: 0.000005
  lr_multi: 40.0
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255
  conf_thresh: 0.95

# arguments for model
  model: dpt
  backbone: dinov2_small
  lock_backbone: True
