# arguments for dataset
dataset: smoke5k
data_root: /home/ych/ijmond-camera-ai/bbox_learn/dataset
nclass: 2
crop_size: 252
base_size: 518  # long side rescaled to this before scale jitter (2x crop_size)

# arguments for training
epochs: 2
batch_size: 60 # per GPU (decrease this if using multiple GPUs to avoid OOM)
lr: 0.00001  # use 0.000005 for single GPU and 0.00001 for 2 GPUs and 0.00002 for 4 GPUs
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: dpt
backbone: dinov2_base
lock_backbone: True
